sudo: required
services:
  - docker

before_install:
  - docker build -t temporary_name -f Dockerfile.dev .

script:
  - docker run -e CI=true temporary_name npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-1-896368497283"
  bucket_path: "docker-react-1"
  on:
    branch: master
    access_key_id: $aws_access_key_id
    secret_access_key:
      secure: "$aws_secret_access_key"
